export const privacyPolicyContent = [
  {
    id: 1,
    description:
      "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
  },
  {
    id: 2,
    description:
      "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
  },
  {
    id: 3,
    description:
      "Interpretation and Definitions Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions.",
  },
  {
    id: 4,
    description:
      "The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
  },
  {
    id: 5,
    description: "Definitions For the purposes of this Privacy Policy:",
  },
  {
    id: 6,
    description:
      "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to vijeet's QuantumMind",
  },
  {
    id: 7,
    description:
      "Affiliate means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. Account means a unique account created for You to access our Service or parts of our Service.",
  },
  {
    id: 8,
    description:
      "Website refers to Vijeet's QuantumMind Project, accessible from https://github.com/vijeet-shah/quantummind Service refers to the Website. Country refers to: Maharashtra, India Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.",
  },
  {
    id: 9,
    description:
      "Personal Data is any information that relates to an identified or identifiable individual. Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  },
  {
    id: 10,
    description:
      "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    id: 11,
    description:
      "Collecting and Using Your Personal Data Types of Data Collected Personal Data While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
  },
  {
    id: 12,
    description:
      "Email address First name and last name Phone number Usage Data Usage Data Usage Data is collected automatically when using the Service.",
  },
];
